### ISSUE TITLE
Unable to add to slack

### ISSUE THREAD

**Issue by Braunson** [dominicrico/slackify#8]
I've tried to add Sonfigy to Slack but get these error details:

```
Unapproved permissions requested
commands
```

**Comment by ehargitt** [comment]
I got the same issue. Might be hanging on this:
```
Songify will be able to view:

View profile details about people in your workspace
```

**Comment by dominicrico** [comment]
Hey @Braunson and @ehargitt,

I'm already in contact with Slack because of that issue. I don't know why, but they removed the "commands" scope from the bot token even though it is need for every bot. I will give you an update as soon as Slack is sending me any answer.

Sorry!

**Comment by dominicrico** [comment]
Hey @Braunson and @ehargitt,

got the message from Slack that everything is up and running again! Could you please check again if you can install the app? 

Thank in advance!

**Comment by Braunson** [comment]
@dominicrico Looks to work now! Thank you.

**Comment by Braunson** [comment]
@dominicrico Quick question, if I'm running this on a team of users, how does everyone else use Songify to display their Spotify music currently playing? I've already added it to the workspace under _my_ user..

**Comment by dominicrico** [comment]
@Braunson each user has to connect itself to songify. That's because of the Slack and Spotify API tokens we need to display the current song within Slack.  So best thing is to share the connect link (https://songify.io/connect) with your team. 

I hope this answers your question.

**Comment by ehargitt** [comment]
Works great! Thanks @dominicrico . Great work, great app

**Comment by dominicrico** [comment]
@ehargitt thank you!
