### ISSUE TITLE
Issue when Spotify isn't running

### ISSUE THREAD

**Issue by Braunson** [dominicrico/slackify#9]
For some reason, I'm not sure when this was caused but now when I have Spotify turned off, it shows me listening 
to one song every time. Then when I start Spotify and play something, it 'll show what I'm listening to, and have normal behavior. Then when Spotify is closed, it'll revert to show I'm listening to the same song (old) again as it did before I turned Spotify on.

I've had to go in and remove the status, but a weird bug.

**Comment by dominicrico** [comment]
Hey @Braunson,
this is because Songify uses your last status as the default status when nothing is running. I will add a command to update the default status as soon as I find time to. Thanks for reporting this.

**Comment by Braunson** [comment]
@dominicrico I figured it did, it seems my default status is cached or something regardless of what song I last played. Thanks. Perhaps an option to "reset" this status either via Songify or when disconnecting the app it 'll revert it?

**Comment by dominicrico** [comment]
@Braunson I added a new command to update the status, when spotify is no longer running. 
With `/songify status :emote: foo bar` you can update your default status to what ever you want, hope that helps!

**Comment by Braunson** [comment]
Thanks @dominicrico this helps!
